### ISSUE TITLE
Deprecated formula for CV processing

### ISSUE THREAD

**Issue by pampi** [mzylowski/resume#4]
https://github.com/mzylowski/resume/blob/d5523997951fe696d20de157b823566a870ad825/cv/cv.tex#L586-L590

According to GDPR regulations, it's deprecated.
https://poradnikpracownika.pl/-co-zmienila-nowa-klauzula-w-cv-po-wejsciu-rodo

**Comment by mzylowski** [comment]
Valid english version:
https://atelierkariery.com/4-aktualne-wzory-klauzuli-cv-wersja-jezyku-angielskim-2019/
```
I agree to the processing of personal data provided in this document for realising the recruitment process pursuant to the Personal Data Protection Act of 10 May 2018 (Journal of Laws 2018, item 1000) and in agreement with Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation).
```
Will be fixed soon.
